name: Run provider pre-processing
on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: impresso-dashboard-runner
    timeout-minutes: 3
    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: Run preprocessing script using latest docker image
      - name: Run preprocessing script
        run: |
          sudo docker run --rm \
            -e PROVIDER_DATA_FOLDER=/data/providers \
            -e CSV_DATA_FOLDER=/data/csv \
            -v ./data/gdrive_metadata:/data/providers \
            -v ${{ secrets.VM_DATA_FOLDER }}:/data/csv \
            impresso-dashboard-preprocessing:latest python /script/preprocessing.py --only_providers --force_reprocess
